# .github/workflows/ci.yml
name: Jekyll Site CI

on:
  pull_request:
  push:
    branches-ignore:
      - main        # run on branch pushes, not on main

jobs:
  verify-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.6'
          bundler-cache: true
          cache-version: 0
      - name: Build with Jekyll
        run: bundle exec jekyll build
