name: Jekyll Site CI

on:
  push:
    branches-ignore:
      - main        # run on branch pushes, not on main
  pull_request:

jobs:
  # Build job
  verify-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.6' # Should match the Gemfile version
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Build with Jekyll
        run: bundle exec jekyll build
